### PR TITLE
Fix misspell in pkg upgrade.

### PR DESCRIPTION
**Pull request by TheKingFireS**
from ``Otions`` to ``Options``
Now, it should works.

### CODE REVIEW

**Comment by phoenixbyrd** [comment]
Thanks, I missed that

**Comment by phoenixbyrd** [comment]
No, just tried, still isn't working :(

**Comment by phoenixbyrd** [comment]
Nevermind, I'm a smooth brain, had it in the wrong command. Working fine now.

**Comment by TheKingFireS** [comment]
Lol.

**Pull request merged**
